/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.proyecto2805;

public class App {
    public String getGreeting() {
        return "Hello luis!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("programacion estructurada");
        System.out.println("hhhh");
    }
}
